[package]
name = "dcc-bot-poise"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = {version = "0.6.1"}
dotenv = "0.15.0"
tokio = { version = "1.44.1" , features = ["rt-multi-thread"] }
fastrand = "2.3.0"
